version: '3'
services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - userservice
      - client

  client:
    build: ./client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./client:/app

  userservice:
    build: ./server/UserService
    env_file:
      - ./server/UserService/.env
    volumes:
      - /app/node_modules
      - ./server/UserService:/app
    depends_on:
      - userdb

  userdb:
    image: mongo:4.4.6
    restart: always
    container_name: userdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - userdb:/data/db

  userdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: userdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - userdb

  postservice:
    build: ./server/PostService
    env_file:
      - ./server/PostService/.env
    volumes:
      - /app/node_modules
      - ./server/PostService:/app
    depends_on:
      - postdb

  postdb:
    image: mongo:4.4.6
    restart: always
    container_name: postdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - postdb:/data/db

  postdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_SERVER: postdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - postdb

volumes:
  userdb:
  postdb:
