version: '3'
services:

  nginx:
    image: sifat1221/linkedin-client
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - userservice
      - postservice
      - notificationservice
      - minioservice

  userservice:
    image: sifat1221/linkedin-backend-userservice
    env_file:
      - ./server/UserService/.env
    volumes:
      - /app/node_modules
      - ./server/UserService:/app
    depends_on:
      - userdb

  userdb:
    image: mongo:4.4.6
    restart: always
    container_name: userdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - userdb:/data/db

  userdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: userdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - userdb

  notificationservice:
    image: sifat1221/linkedin-backend-notificationservice:latest
    env_file:
      - ./server/NotificationService/.env
    volumes:
      - /app/node_modules
      - ./server/NotificationService:/app
    depends_on:
      - notificationdb

  notificationdb:
    image: mongo:4.4.6
    restart: always
    container_name: notificationdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - notificationdb:/data/db

  notificationdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: notificationdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - notificationdb

  postservice:
    image: sifat1221/linkedin-backend-postservice
    env_file:
      - ./server/PostService/.env
    volumes:
      - /app/node_modules
      - ./server/PostService:/app
    depends_on:
      - postdb

  postdb:
    image: mongo:4.4.6
    restart: always
    container_name: postdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - postdb:/data/db

  postdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: postdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - postdb

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodb:/data
    environment:
      MINIO_ROOT_USER: sifat
      MINIO_ROOT_PASSWORD: '01711813256'
    command: server --console-address ":9001" /data

  minioservice:
    image: sifat1221/linkedin-backend-minioservice
    env_file:
      - ./server/MinioService/.env
    volumes:
      - /app/node_modules
      - ./server/MinioService:/app
    depends_on:
      - minio

volumes:
  userdb:
  postdb:
  miniodb:
  notificationdb:
