version: '3'
services:

  nginx:
    image: sifat1221/linkedin-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - userservice
      - postservice
      - notificationservice
      - minioservice

  userservice:
    image: sifat1221/linkedin-backend-userservice
    environment:
      - PORT=5000
      - MONGO_USERNAME=sifat
      - MONGO_PASSWORD=1234
      - MONGO_IP=userdb
      - MONGO_DATABASE_NAME=linkdinUsers
      - PASSWORD_HASH_SECRET_KEY=369b4d397587030ad10c67d03faa437f47c613c4373bac9065b37cf06eb7c3b926f8f7d5e67c93f47485fb75a771e515c171c240d3c202adc82ee18ffc7a1c11
    volumes:
      - /app/node_modules
    depends_on:
      - userdb

  userdb:
    image: mongo:4.4.6
    restart: always
    container_name: userdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - userdb:/data/db

  userdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: userdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - userdb

  notificationservice:
    image: sifat1221/linkedin-backend-notificationservice:latest
    environment:
      - PORT=8000
      - MONGO_USERNAME=sifat
      - MONGO_PASSWORD=1234
      - MONGO_IP=notificationdb
      - MONGO_DATABASE_NAME=linkdinNotifications
    volumes:
      - /app/node_modules
    depends_on:
      - notificationdb

  notificationdb:
    image: mongo:4.4.6
    restart: always
    container_name: notificationdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - notificationdb:/data/db

  notificationdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: notificationdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - notificationdb

  postservice:
    image: sifat1221/linkedin-backend-postservice
    environment:
      - USER_URL=http://userservice:5000/api/user
      - NOTIFICATION_URL=http://notificationservice:8000/api/notification
      - MINIO_URL=http://minioservice:7000/api/objectStorage
      - PORT=6000
      - MONGO_USERNAME=sifat
      - MONGO_PASSWORD=1234
      - MONGO_IP=postdb
      - MONGO_DATABASE_NAME=linkdinPosts
      - PASSWORD_HASH_SECRET_KEY=369b4d397587030ad10c67d03faa437f47c613c4373bac9065b37cf06eb7c3b926f8f7d5e67c93f47485fb75a771e515c171c240d3c202adc82ee18ffc7a1c11
    volumes:
      - /app/node_modules
    depends_on:
      - postdb

  postdb:
    image: mongo:4.4.6
    restart: always
    container_name: postdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sifat
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - postdb:/data/db

  postdb-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: postdb
      ME_CONFIG_MONGODB_ADMINUSERNAME: sifat
      ME_CONFIG_BASICAUTH_USERNAME: sifat
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
    depends_on:
      - postdb

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodb:/data
    environment:
      MINIO_ROOT_USER: sifat
      MINIO_ROOT_PASSWORD: '01711813256'
    command: server --console-address ":9001" /data

  minioservice:
    image: sifat1221/linkedin-backend-minioservice
    environment:
      - PORT =7000
      - ENDPOINT=minio
      - ACCESSKEY=sifat
      - MINIO_SECRET_KEY=01711813256
      - BUCKETNAME= linkdin-post-images
      - REGION= us-east-1
      - MINIO_BASE_URL= http://localhost:9000
    volumes:
      - /app/node_modules
    depends_on:
      - minio

volumes:
  userdb:
  postdb:
  miniodb:
  notificationdb:
